### ISSUE TITLE
Request for Evaluation Code

### ISSUE THREAD

**Issue by LHL3341** [MultimodalGeo/GeoText-1652#3]
Hello,

Thank you for sharing this great dataset! I am currently using it for my research and it has been very helpful. However, I noticed that the evaluation code is not included in the repository. Could you please consider sharing the evaluation code or providing instructions on how to perform the evaluation?

It would be extremely helpful for reproducing the results mentioned in your paper/work.

Thank you again for your contributions!

**Comment by MultimodalGeo** [comment]
Yes. I will updated it in Oct. Thank you for reaching out!
