### ISSUE TITLE
Release GeoText dataset on HF

### ISSUE THREAD

**Issue by NielsRogge** [MultimodalGeo/GeoText-1652#5]
Hi @MultimodalGeo,

Niels here from the open-source team at Hugging Face. I discovered your work through ECCV, congrats, I indexed the paper here: https://huggingface.co/papers/2311.12751 (feel free to claim it). I work together with [AK](https://x.com/_akhaliq) on improving the visibility of researchers' work on the hub.

It'd be great to make the dataset available on the 🤗 hub, rather than Google Drive, to improve its discoverability/ease of use. We can add tags so that people find them when filtering https://huggingface.co/datasets, so that people can do:

```python
from datasets import load_dataset

dataset = load_dataset("your-hf-username-or-organization/geotext")
```

See here for a guide: https://huggingface.co/docs/datasets/loading.

There's then also the dataset viewer which allows people to see the first few rows in the browser: https://huggingface.co/docs/hub/en/datasets-viewer.

This would make the dataset easier accessible, and also discoverable.

We can then also link the dataset to the paper page.

Let us know if you need any help.

Cheers,

Niels
ML Engineer @ HF 🤗

**Comment by MultimodalGeo** [comment]
Dear Niels, thank you for reaching out🤗. I will upload it to the HF.
